# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calc_win(object):
    def setupUi(self, Calc_win):

        self.num_list = []

        Calc_win.setObjectName("Calc_win")
        Calc_win.resize(366, 426)
        Calc_win.setStyleSheet("background-color: rgb(1, 1, 15);\n"
                               "")


        self.centralwidget = QtWidgets.QWidget(Calc_win)
        self.centralwidget.setObjectName("centralwidget")
        self.input = QtWidgets.QLineEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(30, 40, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        #self.centralwidget.setWindowTitle('Calculator')

        self.input.setFont(font)
        self.input.setStyleSheet("QLineEdit{\n"
                                 "    color: rgb(255, 255, 255);\n"
                                 "    border:2px solid rgb(37, 38, 48);\n"
                                 "    border-radius:30px;\n"
                                 "    padding-left:20px;\n"
                                 "    padding-right:20px;\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit:hover{\n"
                                 "    border:2px solid  rgb(119, 0, 255);\n"
                                 "    color: rgb(119, 0, 255);\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit:focus{\n"
                                 "    border:2px solid  rgb(119, 0, 255);\n"
                                 "\n"
                                 "}\n"
                                 "")
        self.input.setAlignment(QtCore.Qt.AlignCenter)
        self.input.setObjectName("input")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(20, 300, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("QPushButton{\n"
                                "    color:rgb(37, 38, 48);\n"
                                "    border:1px solid rgb(37, 38, 48);\n"
                                "    border-radius:10px;\n"
                                "\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color:rgb(119, 0, 255);\n"
                                "\n"
                                "}")
        self.btn1.setObjectName("btn1")
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setGeometry(QtCore.QRect(20, 360, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.btn0.setFont(font)
        self.btn0.setStyleSheet("QPushButton{\n"
                                "    color:rgb(37, 38, 48);\n"
                                "    border:1px solid rgb(37, 38, 48);\n"
                                "    border-radius:10px;\n"
                                "\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color:rgb(119, 0, 255);\n"
                                "\n"
                                "}")
        self.btn0.setObjectName("btn0")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(110, 300, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("QPushButton{\n"
                                "    color:rgb(37, 38, 48);\n"
                                "    border:1px solid rgb(37, 38, 48);\n"
                                "    border-radius:10px;\n"
                                "\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color:rgb(119, 0, 255);\n"
                                "\n"
                                "}")
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(200, 300, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("QPushButton{\n"
                                "    color:rgb(37, 38, 48);\n"
                                "    border:1px solid rgb(37, 38, 48);\n"
                                "    border-radius:10px;\n"
                                "\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color:rgb(119, 0, 255);\n"
                                "\n"
                                "}")
        self.btn3.setObjectName("btn3")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(20, 240, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("QPushButton{\n"
                                "    color:rgb(37, 38, 48);\n"
                                "    border:1px solid rgb(37, 38, 48);\n"
                                "    border-radius:10px;\n"
                                "\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color:rgb(119, 0, 255);\n"
                                "\n"
                                "}")
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(110, 240, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("QPushButton{\n"
                                "    color:rgb(37, 38, 48);\n"
                                "    border:1px solid rgb(37, 38, 48);\n"
                                "    border-radius:10px;\n"
                                "\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color:rgb(119, 0, 255);\n"
                                "\n"
                                "}")
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(200, 240, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("QPushButton{\n"
                                "    color:rgb(37, 38, 48);\n"
                                "    border:1px solid rgb(37, 38, 48);\n"
                                "    border-radius:10px;\n"
                                "\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color:rgb(119, 0, 255);\n"
                                "\n"
                                "}")
        self.btn6.setObjectName("btn6")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(20, 180, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("QPushButton{\n"
                                "    color:rgb(37, 38, 48);\n"
                                "    border:1px solid rgb(37, 38, 48);\n"
                                "    border-radius:10px;\n"
                                "\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color:rgb(119, 0, 255);\n"
                                "\n"
                                "}")
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(110, 180, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.btn8.setFont(font)
        self.btn8.setStyleSheet("QPushButton{\n"
                                "    color:rgb(37, 38, 48);\n"
                                "    border:1px solid rgb(37, 38, 48);\n"
                                "    border-radius:10px;\n"
                                "\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color:rgb(119, 0, 255);\n"
                                "\n"
                                "}")
        self.btn8.setObjectName("btn8")
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(200, 180, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.btn9.setFont(font)
        self.btn9.setStyleSheet("QPushButton{\n"
                                "    color:rgb(37, 38, 48);\n"
                                "    border:1px solid rgb(37, 38, 48);\n"
                                "    border-radius:10px;\n"
                                "\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color:rgb(119, 0, 255);\n"
                                "\n"
                                "}")
        self.btn9.setObjectName("btn9")
        self.equal_btn = QtWidgets.QPushButton(self.centralwidget)
        self.equal_btn.setGeometry(QtCore.QRect(290, 300, 61, 111))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.equal_btn.setFont(font)
        self.equal_btn.setStyleSheet("QPushButton{\n"
                                     "    color:rgb(37, 38, 48);\n"
                                     "    border:1px solid rgb(37, 38, 48);\n"
                                     "    border-radius:10px;\n"
                                     "\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "    background-color:rgb(119, 0, 255);\n"
                                     "\n"
                                     "}")
        self.equal_btn.setObjectName("equal_btn")
        self.divide_btn = QtWidgets.QPushButton(self.centralwidget)
        self.divide_btn.setGeometry(QtCore.QRect(290, 240, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.divide_btn.setFont(font)
        self.divide_btn.setStyleSheet("QPushButton{\n"
                                      "    color:rgb(37, 38, 48);\n"
                                      "    border:1px solid rgb(37, 38, 48);\n"
                                      "    border-radius:10px;\n"
                                      "\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color:rgb(119, 0, 255);\n"
                                      "\n"
                                      "}")
        self.divide_btn.setObjectName("divide_btn")
        self.multiply_btn = QtWidgets.QPushButton(self.centralwidget)
        self.multiply_btn.setGeometry(QtCore.QRect(290, 180, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.multiply_btn.setFont(font)
        self.multiply_btn.setStyleSheet("QPushButton{\n"
                                        "    color:rgb(37, 38, 48);\n"
                                        "    border:1px solid rgb(37, 38, 48);\n"
                                        "    border-radius:10px;\n"
                                        "\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color:rgb(119, 0, 255);\n"
                                        "\n"
                                        "}")
        self.multiply_btn.setObjectName("multiply_btn")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(20, 120, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.clear_btn.setFont(font)
        self.clear_btn.setStyleSheet("QPushButton{\n"
                                     "    color:rgb(37, 38, 48);\n"
                                     "    border:1px solid rgb(37, 38, 48);\n"
                                     "    border-radius:10px;\n"
                                     "\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "    background-color:rgb(119, 0, 255);\n"
                                     "\n"
                                     "}")
        self.clear_btn.setObjectName("clear_btn")
        self.plus_btn = QtWidgets.QPushButton(self.centralwidget)
        self.plus_btn.setGeometry(QtCore.QRect(110, 120, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.plus_btn.setFont(font)
        self.plus_btn.setStyleSheet("QPushButton{\n"
                                    "    color:rgb(37, 38, 48);\n"
                                    "    border:1px solid rgb(37, 38, 48);\n"
                                    "    border-radius:10px;\n"
                                    "\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color:rgb(119, 0, 255);\n"
                                    "\n"
                                    "}")
        self.plus_btn.setObjectName("plus_btn")
        self.minus_btn = QtWidgets.QPushButton(self.centralwidget)
        self.minus_btn.setGeometry(QtCore.QRect(200, 120, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.minus_btn.setFont(font)
        self.minus_btn.setStyleSheet("QPushButton{\n"
                                     "    color:rgb(37, 38, 48);\n"
                                     "    border:1px solid rgb(37, 38, 48);\n"
                                     "    border-radius:10px;\n"
                                     "\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "    background-color:rgb(119, 0, 255);\n"
                                     "\n"
                                     "}")
        self.minus_btn.setObjectName("minus_btn")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(290, 120, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("QPushButton{\n"
                                    "    color:rgb(37, 38, 48);\n"
                                    "    border:1px solid rgb(37, 38, 48);\n"
                                    "    border-radius:10px;\n"
                                    "\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color:rgb(119, 0, 255);\n"
                                    "\n"
                                    "}")
        self.back_btn.setObjectName("back_btn")
        self.dot_btn = QtWidgets.QPushButton(self.centralwidget)
        self.dot_btn.setGeometry(QtCore.QRect(200, 360, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.dot_btn.setFont(font)
        self.dot_btn.setStyleSheet("QPushButton{\n"
                                   "    color:rgb(37, 38, 48);\n"
                                   "    border:1px solid rgb(37, 38, 48);\n"
                                   "    border-radius:10px;\n"
                                   "\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "    background-color:rgb(119, 0, 255);\n"
                                   "\n"
                                   "}")
        self.dot_btn.setObjectName("dot_btn")
        Calc_win.setCentralWidget(self.centralwidget)

        self.clear_btn.clicked.connect(self.clear)

        self.btn0.clicked.connect(lambda: self.number('0'))
        self.btn1.clicked.connect(lambda: self.number('1'))
        self.btn2.clicked.connect(lambda: self.number('2'))
        self.btn3.clicked.connect(lambda: self.number('3'))
        self.btn4.clicked.connect(lambda: self.number('4'))
        self.btn5.clicked.connect(lambda: self.number('5'))
        self.btn6.clicked.connect(lambda: self.number('6'))
        self.btn7.clicked.connect(lambda: self.number('7'))
        self.btn8.clicked.connect(lambda: self.number('8'))
        self.btn9.clicked.connect(lambda: self.number('9'))
        self.dot_btn.clicked.connect(lambda: self.number('.'))

        self.retranslateUi(Calc_win)
        QtCore.QMetaObject.connectSlotsByName(Calc_win)

    def clear(self):
        self.input.setText('')

    def number(self, num):
        self.input.setText(self.input.text() + num)

    def add(self):
        self.num_list.append(self.input.text())


    def retranslateUi(self, Calc_win):
        _translate = QtCore.QCoreApplication.translate
        Calc_win.setWindowTitle(_translate("Calc_win", "MainWindow"))
        self.input.setPlaceholderText(_translate("Calc_win", "Enter Here"))
        self.btn1.setText(_translate("Calc_win", "1"))
        self.btn0.setText(_translate("Calc_win", "0"))
        self.btn2.setText(_translate("Calc_win", "2"))
        self.btn3.setText(_translate("Calc_win", "3"))
        self.btn4.setText(_translate("Calc_win", "4"))
        self.btn5.setText(_translate("Calc_win", "5"))
        self.btn6.setText(_translate("Calc_win", "6"))
        self.btn7.setText(_translate("Calc_win", "7"))
        self.btn8.setText(_translate("Calc_win", "8"))
        self.btn9.setText(_translate("Calc_win", "9"))
        self.equal_btn.setText(_translate("Calc_win", "="))
        self.divide_btn.setText(_translate("Calc_win", "/"))
        self.multiply_btn.setText(_translate("Calc_win", "x"))
        self.clear_btn.setText(_translate("Calc_win", "C"))
        self.plus_btn.setText(_translate("Calc_win", "+"))
        self.minus_btn.setText(_translate("Calc_win", "-"))
        self.back_btn.setText(_translate("Calc_win", "<<<"))
        self.dot_btn.setText(_translate("Calc_win", "."))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Calc_win = QtWidgets.QMainWindow()
    ui = Ui_Calc_win()
    ui.setupUi(Calc_win)
    Calc_win.show()
    sys.exit(app.exec_())
